Первые пункты с 3 по 6 лабы
NSU-FIT-Operating-Systems/21202-operating-systems-part1 pull request #42
Opened 2023-05-28 06:56 UTC by Inventorem

2023-05-28 09:26 UTC, ksilobait requested changes
`zsh: permission denied: ./run.sh`
Git хранит execute bit для всех файлов (но read и write не хранит), нужно добавить этот bit для всех файлов-скриптов, чтобы каждому конечному пользователю не пришлось вруную прописывать `chmod +x ./run.sh`

2023-05-28 09:26 UTC, ksilobait commented on lkurashchenko/lab5/1/5_1.c
> +        printf("Child process terminated with code %d\n", WEXITSTATUS(status));
Добавьте вывод в консоль типа `>>> fork` и `>>> child has updated variables`, чтобы можно было понять, что делает программа, не открывая код только по выводу. Также обновите сообщение в 54 строке, т.к. из него не очевидно, что это сообщение пишет родитель, а не ребенок

2023-05-28 09:26 UTC, ksilobait commented on lkurashchenko/lab6/1/client.c
> +    return EXIT_SUCCESS;
Я не вижу никаких `break` в цикле `while (true)`, чтобы программа завершилась с `EXIT_SUCCESS` и освободила `client_sock`

2023-05-28 09:26 UTC, ksilobait commented on lkurashchenko/lab6/1/server.c
> +        close(server_sock);
`close` является системным вызовом, и может вернуть ошибку. Не помню, вы ли говорили, что видели, что `close` не нужно проверять на ошибку, или кто-то другой.

Если это вы, то, возможно, вы увидели следующее сообщение в `man 2 close`

> Note, however, that a failure return should be used only for diagnostic purposes

Это значит, не то, что не нужно проверять на close, а то, что при ошибке в close максимум, что можно сделать - вывести пользователю (диагностическое сообщение), что что-то не так. То есть при ошибке в `close` нельзя делать повторный `close` или как-то пытаться в коде исправить эту проблему. Но сообщение пользователю все равно нужно вывести, т.к. `silent loss of data` довольно серезная проблема

2023-05-28 09:26 UTC, ksilobait commented on lkurashchenko/lab3/1/run.sh
> +./3_1
Зачем запускать файл в скрипте, если все равно она завершится с EXIT_FAILURE?
Если хотите в скрипте сразу показать, как запускать программу, то переименуйте в `compile.sh` и добавьте `echo "some message"` вместо запуска

2023-05-28 09:26 UTC, ksilobait commented on lkurashchenko/lab3/1/dir/abcd
Я добавил .jpg файл в эту папку, запустил два раза; перевернутый два раза .jpg не открывается.
`hexdump -C` на финальном .jpg файле показывает периодические пробелы
`00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|`

2023-05-31 06:40 UTC, Inventorem commented
> `zsh: permission denied: ./run.sh` Git хранит execute bit для всех файлов (но read и write не хранит), нужно добавить этот bit для всех файлов-скриптов, чтобы каждому конечному пользователю не пришлось вруную прописывать `chmod +x ./run.sh`

Я не могу этого сделать, пишу в CLion на Винде, вставляю в wsl, пишу chmod. Даже если я скрипт с chmod копирую обратно в CLion, git не видит изменений, и я не могу добавить его в коммит

2023-05-31 06:41 UTC, Inventorem commented on lkurashchenko/lab3/1/dir/abcd
Пока исправил всё, кроме вот этого

2023-05-31 06:50 UTC, ksilobait commented
> > `zsh: permission denied: ./run.sh` Git хранит execute bit для всех файлов (но read и write не хранит), нужно добавить этот bit для всех файлов-скриптов, чтобы каждому конечному пользователю не пришлось вруную прописывать `chmod +x ./run.sh`
> 
> Я не могу этого сделать, пишу в CLion на Винде, вставляю в wsl, пишу chmod. Даже если я скрипт с chmod копирую обратно в CLion, git не видит изменений, и я не могу добавить его в коммит

Не понял, как связаны WSL и CLion, WSL это же Linux-терминал внутри Windows, а CLion - IDE внутри Windows
Git инициализирован в определенной директории
Если эта директория в WSL, то причем тут CLion: после `chmod +x run.sh`, `git status` и `git diff` должны отобразить изменения в файле
Если Git находится где-то в Windows (например, в директории проекта CLion), то причем тут WSL: я не знаю, как изменять права доступа в Windows (какой-нибудь icacls или attrib), но не факт, что это сработает

В любом случае всегда можно зайти на сервер, где установлен linux, там сделать `git clone`, `chmod`, `git add`, `git commit` и `git push`

2023-06-01 00:11 UTC, ksilobait requested changes

2023-06-01 00:11 UTC, ksilobait commented on lkurashchenko/lab5/1/5_1.c
> +    printf("%s", DEFALUT_COLOR);
Если дочерний процесс к этому моменту не начал работу (а кроме большого sleep гарантий, что так не будет, нет), то, кажется, будет некорректный вывод. В данной задаче исправлять не нужно, но в общем случае это так называемый "race condition", чего нужно избегать

2023-06-01 00:11 UTC, ksilobait commented on lkurashchenko/lab6/1/client.c
> +    return EXIT_SUCCESS;
Что видит пользователь:
``` bash
./server
```
Как он поймет, что ему вводить, чтобы завершить программу? Исходный код не всегда доступен пользователю, да и вам не нужно лезть в исходный код линукса, чтобы найти исходный код `man` (чтобы узнать, что выйти по `q`) или исходный код `nano` (чтобы узнать, что выйти по `ctrl+x`) - эта информация предоставляется клиенту после запуска процесса

2023-06-01 00:11 UTC, ksilobait commented on lkurashchenko/lab6/1/client.c
> +        if (close(client_sock) == ERROR){
Нет пробела до фигурной скобки, а ниже по коду есть

2023-06-01 00:11 UTC, ksilobait commented on lkurashchenko/lab6/1/client.c
> +        if (close(client_sock) == ERROR){
`){`

2023-06-01 00:11 UTC, ksilobait commented on lkurashchenko/lab6/1/client.c
> +        if (strncmp(buffer, CLIENT_DISCONNECT,10) == 0){
`){`

2023-06-01 02:24 UTC, Inventorem commented on lkurashchenko/lab3/1/dir/abcd
Спросил у ребят, как они делали, исправил на fputc, проблем не стало

2023-06-01 17:24 UTC, ksilobait commented on lkurashchenko/lab6/1/client.c
> +    return EXIT_SUCCESS;
Сейчас единственный способ корректно остановить клиент - это отправить серверу завершающее сообщение, которое остановит еще и сервер, хотя его достаточно было локально проверять, никуда не отправляя (а по желанию для завершения сервера нужно отдельное сообщение)

2023-06-01 17:35 UTC, ksilobait commented on lkurashchenko/lab3/1/dir/abcd
Это скорее не "исправил до", а "downgraded to" 
fread и fwrite читали/писали сразу по несколько байт, а в новой версии на каждый байт отдельный системный вызов, предполагаю, что это "немного" замедлит работу программы; в идеальном решении должны использоваться первые системные вызовы, не fputc

2023-06-01 17:35 UTC, merged