Karpunin lab6
NSU-FIT-Operating-Systems/21202-operating-systems-part1 pull request #43
Opened 2023-05-28 12:54 UTC by GKarpunin

2023-05-30 03:44 UTC, ksilobait requested changes

2023-05-30 03:44 UTC, ksilobait commented on Karpunin/lab6/UDP_server.c
`gcc -Wall`:

``` bash
UDP_server.c: In function ‘main’:
UDP_server.c:47:78: warning: pointer targets in passing argument 6 of ‘recvfrom’ differ in signedness [-Wpointer-sign]
   47 |         readCount = recvfrom(s, buf, 1024, 0, (struct sockaddr * ) & client, & client_address_size);
      |                                                                              ^~~~~~~~~~~~~~~~~~~~~
      |                                                                              |
      |                                                                              int *
In file included from UDP_server.c:4:
/usr/include/sys/socket.h:165:48: note: expected ‘socklen_t * restrict’ {aka ‘unsigned int * restrict’} but argument is of type ‘int *’
  165 |                          socklen_t *__restrict __addr_len);
      |                          ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
```

2023-05-30 03:44 UTC, ksilobait commented on Karpunin/lab6/UDP_server.c
> +            if(close(s) < 0) {
В двух подряд строках разный стиль размещения пробелов

2023-05-30 03:44 UTC, ksilobait commented on Karpunin/lab6/UDP_server.c
> +                printf("Could not close socket file\n");
Почему ниже используется perror, а тут printf?
> close() returns zero on success.  On error, -1 is returned, and errno is set to indicate the error.

2023-05-30 03:44 UTC, ksilobait commented on Karpunin/lab6/UDP_server.c
> +            perror("could not recieve msg");
В случае ошибки close `errno` от close перетрет `errno` от recvfrom

2023-05-30 03:44 UTC, ksilobait commented on Karpunin/lab6/UDP_server.c
> +        printf("Server recieved: %s\n\n", buf);
received

2023-05-30 03:44 UTC, ksilobait commented on Karpunin/lab6/UDP_server.c
> +        if (strcmp(buf, exitMessage) == 0) {
Как пользователь узнает кодовое слово завершения сервера, не заглядывая в исходные файлы? Например, `man` отображает внизу `press h for help or q to quit`, и там не нужно заходить в исходные файлы линукса, чтобы понять, как выйти

2023-05-30 03:44 UTC, ksilobait commented on Karpunin/lab6/UDP_client.c
> +            printf("OK, shutting down the server\n");
Если написать `shutdown` клиенту, он завершит сервер?

2023-05-30 06:06 UTC, GKarpunin commented on Karpunin/lab6/UDP_server.c
Я читал про эти ошибки, у меня не получилось от них избавиться. Там какие-то внутренние проблемы тех разработчиков, которые это придумывали. То ли у них указатель на int, то ли  socklen_t * restrict, что в сущности то же самое.

2023-05-30 07:32 UTC, ksilobait commented on Karpunin/lab6/UDP_server.c
Это не помогает?
https://stackoverflow.com/questions/27620214/differ-in-signedness-warning

2023-05-31 03:15 UTC, ksilobait commented on Karpunin/lab6/UDP_server.c
> +                printf("Could not close socket file\n");
Все еще не везде исправлено

2023-05-31 03:26 UTC, ksilobait commented on Karpunin/lab6/UDP_server.c
> +        if (strcmp(buf, exitMessage) == 0) {
Не исправлено
Пользователь запускает сервер, все, что ему отображается - это порт и готовность принимать сообщения от клиентов, а под капотом сервер ожидает от пользователя кодовое слово, про которое он так и не узнает

2023-05-31 03:31 UTC, ksilobait commented on Karpunin/lab6/UDP_client.c
> +            printf("OK, shutting down the server\n");
Кажется, нужно было исправить строку в printf
Если клиент действительно умеет завершать сервер, то это странное поведение: это как сделать в телеграме две кнопки, закрыть окно и закрыть сервер телеграма (что отключит миллион других клиентов, которые были подключены к этому серверу)
А вообще советую почитать подробнее про UDP, и как отправляются сообщения между сервером и клиентом

2023-06-01 00:44 UTC, ksilobait requested changes

2023-06-01 00:44 UTC, ksilobait commented on Karpunin/lab6/UDP_client.c
Вы пробовали запустить программу после изменений?

2023-06-01 17:07 UTC, merged