lab3
NSU-FIT-Operating-Systems/21202-operating-systems-part1 pull request #6
Opened 2023-03-20 09:44 UTC by Xisepe

2023-03-23 13:39 UTC, ksilobait requested changes

2023-03-23 13:39 UTC, ksilobait commented on golubevm/lab3/lab3-1.c
> +  close(out);
При компиляции появляется warning
> lab3-1.c:127:1: warning: control reaches end of non-void function [-Wreturn-type]

Желательно исправлять все warning, чтобы не было неожиданных поведений во время исполнения

2023-03-23 13:39 UTC, ksilobait commented on golubevm/lab3/lab3-1.c
Не получается запустить на сервере и локально при вызове `./lab3 test` и `./lab3 ./test`
`Cannot create reverse dir` либо `Cannot open reverse dir: Bad file descriptor`
Нужен полностью абсолютный путь?
Рекомендую добавить в код (для более полного отображения ошибок) для методов, которые в man упоминают `errno`
```
#include <errno.h>
if (some_failure) {
    fprintf(stderr, "%s\n", strerror(errno));
}
```

2023-03-23 13:39 UTC, ksilobait commented on golubevm/lab3/lab3-1.c
> +  int outFd = open(tmp, O_RDONLY | O_DIRECTORY);
Обращение к `tmp` после `free` выглядит подозрительно

2023-04-17 16:20 UTC, ksilobait requested changes

2023-04-17 16:20 UTC, ksilobait commented on golubevm/lab3/1/lab3-1.c
> +int reverseFile(reverse_entry_t *entry);
В одном файле нужно придерживаться одного стиля наименования - CamelCase или snake_case, но не обоих

2023-04-17 16:20 UTC, ksilobait commented on golubevm/lab3/1/lab3-1.c
> +    fprintf(stderr, "%s\n", "No path passed via program arguments. Required two arguments");
Можно сразу в ошибке и указать, какие аргументы нужно передать, чтобы не обращаться к readme

2023-04-17 16:20 UTC, ksilobait commented on golubevm/lab3/1/lab3-1.c
> +        close(source_dir_fd);
`man close`:
> A careful programmer will check the return value of close(), since it is quite possible that errors on a previous write(2) operation are reported only on the final close() that releases the open file description.  Failing to check the return value when closing a file may lead to silent loss of data.

2023-04-17 16:20 UTC, ksilobait commented on golubevm/lab3/1/lab3-1.c
> +        close(source_dir_fd);
Я думаю, можно придумать способ уменьшить переиспользование кода освобождающего ресурсы

2023-04-17 16:20 UTC, ksilobait commented on golubevm/lab3/2/lab3-2.c
> +  	mkd:
Удобнее было бы переместить описание команд над соответствующими методами, т.к. полное описание уже есть в readme

2023-04-17 16:20 UTC, ksilobait commented on golubevm/lab3/2/lab3-2.c
> +  		Prints all files contained in quered directory.
queried

2023-04-17 16:20 UTC, ksilobait commented on golubevm/lab3/2/lab3-2.c
> +	   printf("Information for %s\n", filename);
Отсупы съехали

2023-04-17 16:20 UTC, ksilobait commented on golubevm/lab3/2/lab3-2.c
> +	if(stat(filename, &fileStat) < 0)
Нужен единый стиль - либо `if(`, либо `if (`

2023-04-17 16:20 UTC, ksilobait commented on golubevm/lab3/2/lab3-2.c
> +	int wrt = write(1,buf,rd);
`(1, buf, rd)`

2023-04-17 16:20 UTC, ksilobait commented on golubevm/lab3/2/lab3-2.c
> +	char * start_ptr = str;
`char*`?

2023-04-17 16:20 UTC, ksilobait commented on golubevm/lab3/3/lab3-3.c
> +	if (argc < 2) {
`< 3` (или `!= 3`)

2023-04-17 16:20 UTC, ksilobait commented on golubevm/lab3/3/lab3-3.c
> +		sprintf(buf, "/proc/self/pagemap");
Зачем нужен буфер, если можно сразу открыть файл через `open` (или `fopen` с последующим `fileno`)?

2023-04-17 16:20 UTC, ksilobait commented on golubevm/lab3/3/lab3-3.c
> +	if (pagemap_get_entry(&entry, fd, (uint64_t) strtol(argv[2], NULL, 16)) < 0) {
Этот код (который использует pagemap_get_entry) локально запустился (я его детально не рассматривал)

https://github.com/cirosantilli/linux-kernel-module-cheat/blob/25f9913e0c1c5b4a3d350ad14d1de9ac06bfd4be/kernel_module/user/pagemap_dump.c

2023-05-12 16:11 UTC, ksilobait requested changes

2023-05-12 16:11 UTC, ksilobait commented on golubevm/lab3/1/Makefile
> +$(EXE): $(SOURCE)
Проверяйте задачи перед отправкой - эта задача даже не собирается
```
gcc -Wall -O3 lab3-1.c -o rvs
lab3-1.c: In function ‘main’:
lab3-1.c:100:11: error: ‘res’ undeclared (first use in this function)
  100 |       if (res) {
      |           ^~~
lab3-1.c:100:11: note: each undeclared identifier is reported only once for each function it appears in
make: *** [Makefile:9: rvs] Error 1
```

2023-05-12 16:11 UTC, ksilobait commented on golubevm/lab3/1/lab3-1.c
> +    close(source_dir_fd);
Нужно вынести освобождение ресурсов в отдельный метод, потому что тут сильно дублируется код. Плюс нигде у `close` тут не проверяется возвращаемое значение

https://stackoverflow.com/questions/19056309/not-checking-closes-return-value-how-serious-really

2023-05-12 16:11 UTC, ksilobait commented on golubevm/lab3/2/Makefile
> +$(EXE): $(SOURCE)
При возможности вывод не должен содержать никаких предупреждений
```
lab3-2.c: In function ‘fprint’:
lab3-2.c:191:10: warning: suggest parentheses around assignment used as truth value [-Wparentheses]
  191 |   while (rd = read(fd, buf, SIZE)) {
      |          ^~
for name in mkd rmd lsd crt fprint rmf smlk smlprint hrdlk fstt chmd; do\
        ln lab3-2.out $name;\
```

2023-05-12 16:11 UTC, ksilobait commented on golubevm/lab3/2/Makefile
> +$(EXE): $(SOURCE)
Ко второй задаче больше нет замечаний, это замечание не очень критичное, задача засчитана

2023-05-12 16:11 UTC, ksilobait commented on golubevm/lab3/3/lab
В репизотории не должно быть бинарных файлов

2023-05-12 16:11 UTC, ksilobait commented on golubevm/lab3/3/lab3-3.c
Проверяйте задачи перед отправкой на ревью - этот файл не компилируется
```
lab3-3.c: In function ‘pagemap_get_entry’:
lab3-3.c:37:12: warning: zero-length gnu_printf format string [-Wformat-zero-length]
   37 |     printf("")
      |            ^~
lab3-3.c:37:15: error: expected ‘;’ before ‘entry’
   37 |     printf("")
      |               ^
      |               ;
   38 |     entry->pfn = data & (((uint64_t)1 << 54) - 1);
      |     ~~~~~      
```

2023-05-12 16:11 UTC, ksilobait commented on golubevm/lab3/3/prc
бинарный файл

2023-05-12 16:11 UTC, ksilobait commented on golubevm/lab3/3/lab3-3.c
А запускать бинарный файл без компиляции я не могу - я не могу быть уверенным, что файл соответствует коду в .c файле

2023-05-12 16:11 UTC, ksilobait commented on golubevm/lab3/3/lab3-3.c
> +		fprintf(stderr, "Not enough arguments. Required: [pid] [vaddr]");
Разные отступы в одном файле - табуляция и пробелы. Особенно это видно в pull request в github

2023-05-12 16:11 UTC, ksilobait commented on golubevm/lab3/3/lab3-3.c
> +{
Разные переносы строк до/после `{` в одном файле

2023-05-12 16:11 UTC, ksilobait commented on golubevm/lab3/3/lab3-3.c
> +	int fd = open(buf, O_RDONLY);
Как для каждого malloc должен быть свой free, так и тут - для каждого open должен быть close

2023-05-16 06:41 UTC, Xisepe commented on golubevm/lab3/3/lab3-3.c
временно удалил данный таск, если успею доделаю

2023-05-16 06:41 UTC, Xisepe commented on golubevm/lab3/3/lab3-3.c
> +		fprintf(stderr, "Not enough arguments. Required: [pid] [vaddr]");
временно удалил данный таск, если успею доделаю

2023-05-16 06:41 UTC, Xisepe commented on golubevm/lab3/3/lab3-3.c
> +{
временно удалил данный таск, если успею доделаю

2023-05-16 06:41 UTC, Xisepe commented on golubevm/lab3/3/lab3-3.c
> +	int fd = open(buf, O_RDONLY);
временно удалил данный таск, если успею доделаю

2023-05-21 16:20 UTC, ksilobait commented on golubevm/lab3/1/lab3-1.c
> +  close(fd);
Эти тоже надо было бы обработать, ну да ладно уже

2023-05-21 16:26 UTC, ksilobait approved these changes

2023-05-21 16:26 UTC, merged