Abiryukov2 lab2 done
NSU-FIT-Operating-Systems/21202-operating-systems-part1 pull request #7
Opened 2023-03-24 14:37 UTC by A-B-asdf

2023-03-25 05:33 UTC, A-B-asdf commented
Измерить время для разных способов сделать сискол, чекнуть отсылку к vdso, там какое-то замедление

2023-03-30 16:06 UTC, ksilobait commented
В этом pull request должна отображаться толкьо вторая задача в коммитах. В текущий момент основой для ветки abiryukov2_lab2 выбран коммит, который не содержит изменений из main (в том числе уже замерженной первой задачи). 

![image](https://user-images.githubusercontent.com/17474821/228895904-692f07a5-1109-41c4-b7ed-9c054ad68d28.png)

Есть несколько решений:
- merge ветки main в ветку abiryukov2_lab2
- rebase ветки abiryukov2_lab2 на ветку main
- закрытие этого pull request и открытие нового с текущей ветки main

2023-03-31 16:14 UTC, ksilobait requested changes

2023-03-31 16:14 UTC, ksilobait commented on abiryukov2/README.md
Не стоит коммитить лишние файлы, этот readme нужен только для корневой директории

2023-03-31 16:14 UTC, ksilobait commented on abiryukov2/2/1/a/iii/hello_syscall.c
> +  write(STDOUT_FILENO, "Hello world\n", 13);
`syscall`

2023-03-31 16:14 UTC, ksilobait commented on abiryukov2/2/1/b/index.html
Не нужно коммитить лишние файлы (вывод strace не интересует в данной задаче)

2023-03-31 16:14 UTC, ksilobait commented on abiryukov2/2/2/hello
Не нужно коммитить лишние файлы - бинарные файлы не стоит размещать в репозитории

2023-03-31 16:14 UTC, ksilobait commented on abiryukov2/2/3/asdf.c
> +    child_pid = fork();
`fork` может вернуть ошибку, в коде она не проверяется

2023-05-22 15:15 UTC, ksilobait commented
Можно проверять? Я не нахожусь сейчас в assignees
Еще нужно конфликты с веткой main решить

2023-05-23 00:47 UTC, closed without merging