Bochkarev lab1 lab2 lab3(1/3)
NSU-FIT-Operating-Systems/21202-operating-systems-part1 pull request #9
Opened 2023-04-15 05:37 UTC by EBochkarev

2023-04-21 16:31 UTC, ksilobait requested changes

2023-04-21 16:31 UTC, ksilobait commented on Bochkarev/lab1/4/hello.c
> +    char* error;
Обычно пишут либо `char* c`, либо `char *c`, но в этом файле одновременно два стиля записи

2023-04-21 16:31 UTC, ksilobait commented on Bochkarev/lab1/4/hello.c
> +        printf ("%s\n", error);
Пробел обычно не пишут между названием метода и передаваемыми аргументами

2023-04-21 16:31 UTC, ksilobait commented on Bochkarev/lab1/4/hello.c
> +        return(1);
Тут тоже разный стиль кода в одном файле - `return(1)` и `return 0`

2023-04-21 16:31 UTC, ksilobait commented on Bochkarev/lab1/4/hello.c
> +    if ((error = dlerror()) != NULL)  {
Лишний пробел до `{`

2023-04-21 16:31 UTC, ksilobait commented on Bochkarev/lab2/hello_func
Нужно удалить все бинарные файлы из репозитория, они не версионируются гитом (невозможно сделать diff между двумя бинарниками), занимают много места и могут быть несовместимыми с конечной операционной системой

2023-04-21 16:31 UTC, ksilobait commented on Bochkarev/lab2/hello_func.c
> +    print("Hello world!\n");
Два разных вида табуляции в одном файле (4 пробела и `/t`): некоторые текстовые редакторы настроены на отображение одного `\t` символа на 2 или 8 пробелов

2023-04-21 16:31 UTC, ksilobait commented on Bochkarev/lab2/hello_nosyscall.c
> +	register char*  arg2        asm("rsi") = buf;
Тут тоже разная табуляция в начале строк в рамках одного файла

2023-04-21 16:31 UTC, ksilobait commented on Bochkarev/lab2/hello_sys.c
> +    	return 1;
Разная табуляция в рамках одного файла

2023-04-21 16:31 UTC, ksilobait commented on Bochkarev/lab3/1.c
Файлы желательно компилировать в строгом режиме: `gcc -Wall 1.c` выводит
```
1.c: In function ‘main’:
1.c:101:13: warning: unused variable ‘isCreated’ [-Wunused-variable]
  101 |         int isCreated = mkdir(path, 0700);
      |             ^~~~~~~~~
```

2023-04-21 16:31 UTC, ksilobait commented on Bochkarev/lab3/1.c
В директории отсутсвует readme с инструкцией запуска, отсутствует .sh скрипт с тестовым примером запуска, при запуске параметров без аргументов кажется, что программа зависает (т.к. ничего не выводит пользователю). 
В итоге без чтения кода (и нахождения строки `scanf("%s", path)`) непонятно, что делать с программой. Нужен один из способов выше (или какой-нибудь еще), чтобы пользователь мог запустить программу без чтения исходного кода

2023-04-21 16:31 UTC, ksilobait commented on Bochkarev/lab3/1.c
Любые входные данные программа должна корректно отрабатывать и не завершаться критически (даже если ошибка скорее всего никогда не появится, но потенциально возможна вроде отсутствия новой памяти под malloc)
```
> ./a.out
> ab
zsh: segmentation fault (core dumped)  ./a.out
```
Скорее всего эта ошибка исправится после обработки возвращаемых значений от системных вызовов

`man 2 open`:
> RETURN VALUE
       On success, open(), openat(), and creat() return the new file descriptor (a nonnegative integer).  On error, -1 is returned and errno is set to indicate the error.

`man 2 lseek`:
> RETURN VALUE
       Upon successful completion, lseek() returns the resulting offset location as measured in bytes from the beginning of the file.  On error, the value (off_t) -1 is returned and errno is set to indicate the error.

`man 2 write`:
> RETURN VALUE
       On success, the number of bytes written is returned.  On error, -1 is returned, and errno is set to indicate the error.
```

2023-05-09 04:49 UTC, ksilobait commented on Bochkarev/lab1/4/hello.c
> +        return(1);
Все еще не исправлено (и нет комментариев в pull request, почему код так выглядит), но замечание не критичное, зачтено

2023-05-09 06:11 UTC, ksilobait commented on Bochkarev/lab3/1.c
Все еще много предупреждений при компиляции с флагом `-Wall`
```
3.1.c: In function ‘getByteNumber’:
3.1.c:55:50: error: expected ‘;’ before ‘return’
   55 |                 printf("Problems setting offset")
      |                                                  ^
      |                                                  ;
   56 |                 return -1;
      |                 ~~~~~~                            
3.1.c: In function ‘main’:
3.1.c:124:40: error: expected ‘;’ before ‘if’
  124 |         printf("Enter path to folder:")
      |                                        ^
      |                                        ;
  125 |         if(scanf("%s", path) <= 0)
      |         ~~                              
3.1.c:132:16: error: ‘startPath’ undeclared (first use in this function)
  132 |         strcpy(startPath, path);
      |                ^~~~~~~~~
3.1.c:132:16: note: each undeclared identifier is reported only once for each function it appears in
3.1.c:137:62: error: expected ‘;’ before ‘}’ token
  137 |                 printf("Problems with creating new folder\n")
      |                                                              ^
      |                                                              ;
  138 |         }
      |         ~                                                     
```

2023-05-09 07:22 UTC, ksilobait requested changes

2023-05-09 07:22 UTC, ksilobait commented on Bochkarev/lab3/3.1.c
> +	if(mkdir(path, 0700) != 0)
Сначала нужно проверить на наличие исходной директории, прежде чем создавать конечную. Мало того, что каждый некорректный вызов программы (передавая несуществующую директорию) создает побочные эффекты, так еще и при передаче симметричного пути (например, 'aba' или 'a') программа успешно завершается

2023-05-09 07:22 UTC, ksilobait commented on Bochkarev/lab3/3.1.c
> +	if(close(fd1) == -1 || close(fd2) == -1)
В Си есть short-circuit evaluation. а в этом месте хотелось бы попробовать закрыть fd2 даже если fd1 не закрылся

2023-05-09 07:22 UTC, ksilobait commented on Bochkarev/lab3/3.1.c
> +			return -1;
Нужно освободить ресурсы перед уходом из метода (я не вижу `close(fd)` снаружи этого метода)

2023-05-09 07:22 UTC, ksilobait commented on Bochkarev/lab4/4.2.2_Heap.c
> +	char* p = mmap(NULL, block * 10, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0);
Нужна проверка на MAP_FAILED

2023-05-09 07:22 UTC, ksilobait commented on Bochkarev/lab4/4.2.2_Heap.c
> +void handler(int sig)
Первый warning можно исправить добавив все нужные аргументы в handler (даже если они не будут далее использоваться)

```
4.2.2_Heap.c: In function ‘catchSigSegv’:
4.2.2_Heap.c:18:25: warning: assignment to ‘void (*)(int,  siginfo_t *, void *)’ from incompatible pointer type ‘void (*)(int)’ [-Wincompatible-pointer-types]
   18 |         sa.sa_sigaction = &handler;
      |                         ^
4.2.2_Heap.c: In function ‘addHeap’:
4.2.2_Heap.c:29:13: warning: unused variable ‘size’ [-Wunused-variable]
   29 |         int size = 0;
      |             ^~~~
```

2023-05-09 07:22 UTC, ksilobait commented on Bochkarev/lab4/4.2.2_Heap.c
> +	sigaction(SIGSEGV, &sa, NULL);
Нужна проверка возвращаемого значения

2023-05-09 07:22 UTC, ksilobait commented on Bochkarev/lab4/4.2.2_Heap.c
> +	mprotect(p, block * 10, PROT_NONE);
Нужна проверка возвращаемого значения

2023-05-09 07:22 UTC, ksilobait commented on Bochkarev/lab5/5.1.c
Большое число предупреждений при компиляции с флагом `-Wall`, на первый взгляд все можно легко исправить

2023-05-10 00:48 UTC, EBochkarev commented on Bochkarev/lab5/5.1.c
Осталось одно предупреждение. Инициализация переменной там не нужна, а если её проинициализировать (даже нулл), то sigsegv будет в waitpid

2023-05-10 01:00 UTC, EBochkarev commented on Bochkarev/lab3/3.1.c
> +			return -1;
fd у меня в программе нигде нет, а fd1 и fd2 я закрываю в конце этой функции

2023-05-10 16:30 UTC, ksilobait requested changes

2023-05-10 16:30 UTC, ksilobait commented on Bochkarev/lab3/3.1.c
> +		printf("Directory does not exist\n");\
Для этого есть функция `perror`, которая автоматически обрабатывает последний `errno` в человекочитаемый формат для всех возможных errno

2023-05-10 16:30 UTC, ksilobait commented on Bochkarev/lab3/3.1.c
> +			return -1;
Да, я имел в виду fd1 и fd2

Проблема в том, что выполнение программы не всегда дойдет до конца этой функции и до close: если будет ошибка в read, то `return -1;` вернет исполнение в main, а `close` не будет исполнен, хотя файлы были успешно открыты к этому времени

2023-05-10 16:30 UTC, ksilobait commented on Bochkarev/lab4/4.2.2_Heap.c
> +	sigaction(SIGSEGV, &sa, NULL);
В выводе программы я вижу `Sigaction failure`. Для проверки в чем причина лучше использовать `perror` вместо `printf`. В этом случае `perror` возвращает "Success", то есть `sigaction` завершился корректно - нужно внимательнее прочитать секцию "RETURN VALUE" в `man sigaction`

2023-05-10 16:30 UTC, ksilobait commented on Bochkarev/lab5/5.1.c
Я запускал с флагом `-Wpedantic`, что и генерировало большое число других предупреждений (про каст к void*), их не обязательно исправлять

2023-05-10 16:30 UTC, ksilobait commented on Bochkarev/lab5/5.1.c
Ни одна задача не должна падать с ошибкой `Segmentation fault (core dumped)` (а 5.1.c падает)

2023-05-11 02:41 UTC, EBochkarev commented on Bochkarev/lab5/5.1.c
![image](https://github.com/NSU-FIT-Operating-Systems/21202-operating-systems-part1/assets/124948925/c661f88b-72e9-47dd-89a5-7cbd506ef2f6)

2023-05-11 02:41 UTC, EBochkarev commented on Bochkarev/lab5/5.1.c
Как вы запускаете задачу? У меня не падает, я перепроверил.

2023-05-12 16:30 UTC, ksilobait commented on Bochkarev/lab5/5.1.c
Упало локально на моем ноутбуке, для этих ситуаций как раз существует общий сервер, где можно провести контрольную проверку:
```
guru@ub22-gr-02:~/21202-operating-systems-part1$ git rev-parse --short HEAD
590d038

guru@ub22-gr-02:~/21202-operating-systems-part1$ cd Bochkarev/lab5/

guru@ub22-gr-02:~/21202-operating-systems-part1/Bochkarev/lab5$ gcc 5.1.c 

guru@ub22-gr-02:~/21202-operating-systems-part1/Bochkarev/lab5$ ./a.out 
local: 10 0x7fffe0e4b368
global: 20 0x559438f82010
parent pid: 1249294
child pid 1249295
(child) pid: 1249295 parent pid: 1249294
(child) local: 10 0x7fffe0e4b368 global: 20 0x559438f82010
(child - changed) local: 5 0x7fffe0e4b368 global: 7 0x559438f82010
(parent - changed in child) local: 10 0x7fffe0e4b368 global: 20 0x559438f82010
Segmentation fault (core dumped)
```

2023-05-24 12:12 UTC, EBochkarev commented on Bochkarev/lab3/3.1.c
> +			return -1;
fixed

2023-05-25 16:26 UTC, ksilobait requested changes

2023-05-25 16:26 UTC, ksilobait commented on Bochkarev/lab6/server.c
> +    int clSocket = 0;
Интересно, как у вас похож код 6 задания на код Некрасова (либо ваш код похож на какой-то третий, к которому у меня нет доступа) вплоть до ошибок:

```sh
   gcc -Wall -Werror server.c 
server.c: In function ‘main’:
server.c:53:89: error: pointer targets in passing argument 6 of ‘recvfrom’ differ in signedness [-Werror=pointer-sign]
   53 |         readCount = recvfrom(sSocket, buf, BUFFER_SIZE, 0, (struct sockaddr *) &clAddr, &addrLen);
      |                                                                                         ^~~~~~~~
      |                                                                                         |
      |                                                                                         int *
In file included from server.c:5:
/usr/include/sys/socket.h:165:48: note: expected ‘socklen_t * restrict’ {aka ‘unsigned int * restrict’} but argument is of type ‘int *’
  165 |                          socklen_t *__restrict __addr_len);
      |                          ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
server.c:36:9: error: unused variable ‘clSocket’ [-Werror=unused-variable]
   36 |     int clSocket = 0;
      |         ^~~~~~~~
cc1: all warnings being treated as errors
```

2023-05-25 16:26 UTC, ksilobait commented on Bochkarev/lab6/server.c
> +    		exit(EXIT_FAILURE);
В файле табуляция должна быть одного типа

2023-05-25 16:29 UTC, ksilobait commented
Обычно PR - законченная задача, для которой остался только код ревью.
Желательно создавать один PR на одну задачу, а не постоянно добавлять в существующий новые подзадачи

2023-05-26 03:33 UTC, EBochkarev commented on Bochkarev/lab6/server.c
> +    int clSocket = 0;
Это example код по теме для recvfrom

2023-05-26 04:04 UTC, EBochkarev commented
> 

Это через много веток делать? Тогда получится что на каждого человека по 6 веток будет. Обычно я просто в мейн заливаю с веток по одной лабе. А тут  у нас один общий мейн.

2023-05-26 14:13 UTC, ksilobait commented
> Это через много веток делать? Тогда получится что на каждого человека по 6 веток будет. Обычно я просто в мейн заливаю с веток по одной лабе. А тут у нас один общий мейн.

Не понял, в чем именно проблема

Если проблема в общем main на файловой системе, то там у каждого своя директория.
Если проблема в общей ветке main, то это, как при обычном процессе разработки (одна главная ветка main/master/develop на весь проект).
Если проблема в куче своих веток, то (см. скриншот) многие UI гит-клиенты интерпретируют `/` разделитель в имени ветки как вложенную ветку, что облегчает процесс поиска нужной ветки в UI клиентах.
![image](https://github.com/NSU-FIT-Operating-Systems/21202-operating-systems-part1/assets/17474821/a4ef9eeb-002d-4356-ad9d-6adb5ae1cddc)

А проблема одного пулл реквеста, что мне сложно отслеживать, что я уже проверил, а что было недавно добавлено. А в данном случае уже ничего не нужно исправлять, замечание на будущее

2023-05-26 14:24 UTC, ksilobait commented on Bochkarev/lab6/server.c
> +    int clSocket = 0;
Не понял, что значит "example код". Код должен соответствовать правилам (особенно последние задачи, т.к. я уже до 5 раз до этого указывал на одни и те же проблемы), в том числе про запуск с максимально возможным числом флагов предупреждения. Копировать задачи с лекций / мануалов / stackoverflow / других сайтов и источников без исправления очевидных замечаний не стоит

2023-05-27 01:05 UTC, EBochkarev commented on Bochkarev/lab6/server.c
> +    int clSocket = 0;
Я пофиксил. Сори за то что без -Wall скомпилировал, я понимаю что вам не оч круто каждый раз одно и тоже писать. Просто всю жизнь просто так компилил и на этом курсе в первый раз услышал про это.

2023-05-27 01:05 UTC, EBochkarev commented on Bochkarev/lab6/server.c
> +    		exit(EXIT_FAILURE);
Я пофиксил.

2023-05-28 07:23 UTC, ksilobait requested changes

2023-05-28 07:23 UTC, ksilobait commented on Bochkarev/lab6/client.c
> +    close(clSocket);
Я, как пользователь, в общем случае хотел бы знать, что данные могли не записаться в файл

2023-05-28 07:23 UTC, ksilobait commented on Bochkarev/lab6/client.c
> +    return EXIT_SUCCESS;
Я не вижу вариантов исполнения сервера, когда он завершится с `SUCCESS`

2023-05-28 09:17 UTC, EBochkarev commented on Bochkarev/lab6/client.c
> +    close(clSocket);
Сделал.

2023-05-28 09:17 UTC, EBochkarev commented on Bochkarev/lab6/client.c
> +    return EXIT_SUCCESS;
Сделал.

2023-05-30 03:08 UTC, merged